server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: product
  datasource:
    platform: h2
    url: jdbc:h2:mem:products
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddp: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
  jmx:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    compatibility-verifier:
      enabled: false

crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.product.routingkey

security:
  jwt:
    token:
      secret-key: chave_microservices  #chave de assinatura do token

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/registry/eureka
