server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:products
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddp: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
