server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: gateway
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      import-check:
        enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/registry/eureka

zuul:
  prefix: /api
  ignoringServices: "*"

  routes:
    products:
      path: /products/**
      service-id: product
      strip-prefix: false
      custom-sensitive-headers: true

    payments:
      path: /payments/**
      service-id: payment
      strip-prefix: false
      custom-sensitive-headers: true

    auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true
