version: '3'

services:
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-cloud-netflix
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_pass
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
volumes:
  rabbitmq:

networks:
  spring-cloud-netflix:
    ipam:
      config:
        - subnet: 10.8.0.0/27
