server:
  port: 8761
  servlet:
    context-path: /registry

spring:
  application:
    name: registry
  cloud:
    config:
      import-check:
        enabled: false
    compatibility-verifier:
      enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
