server:
  port: 8761
  servlet:
    context-path: /registry
spring:
  application:
    name: registry
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: 'http://${eureka.instance.hostname}:${server.port}/eureka/'
